version: "3.5"
services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "${WARDEN_ENV_NAME}-mariadb"
    image: ${WARDEN_IMAGE_REPOSITORY}/mariadb:${MARIADB_VERSION:-10.4}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-app}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    hostname: "${WARDEN_ENV_NAME}-phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.priority=3
      - traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.rule=Host(`phpmyadmin.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-phpmyadmin.loadbalancer.server.port=80

volumes:
  dbdata:
